name: Build ZMK Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout user config
        uses: actions/checkout@v3

      - name: Checkout ZMK
        uses: actions/checkout@v3
        with:
          repository: zmkfirmware/zmk
          path: zmk

      - name: Build Corne Left
        uses: zmkfirmware/zmk/actions/build@main
        with:
          board: nice_nano_v2
          shield: corne_left nice_view_adapter

      - name: Build Corne Right
        uses: zmkfirmware/zmk/actions/build@main
        with:
          board: nice_nano_v2
          shield: corne_right nice_view_adapter
