name: Build ZMK Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout user config
        uses: actions/checkout@v3

      - name: Checkout ZMK
        uses: actions/checkout@v3
        with:
          repository: zmkfirmware/zmk
          path: zmk

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install west
        run: |
          pip install --upgrade west

      - name: Initialize west
        run: |
          west init workspace
          cd workspace
          west update

      - name: Build Corne Left
        run: |
          cd workspace
          west build -s ../zmk/app -d build/left -b nice_nano_v2 -- -DSHIELD=corne_left nice_view_adapter

      - name: Build Corne Right
        run: |
          cd workspace
          west build -s ../zmk/app -d build/right -b nice_nano_v2 -- -DSHIELD=corne_right nice_view_adapter

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            workspace/build/left/zephyr/zmk.uf2
            workspace/build/right/zephyr/zmk.uf2
