name: Build ZMK Firmware

on:
  push:
    branches:
      - main

jobs:
  build-left:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: zmkfirmware/zmk-build-action@main
        with:
          shield: corne_left nice_view_adapter
          board: nice_nano_v2

  build-right:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: zmkfirmware/zmk-build-action@main
        with:
          shield: corne_right nice_view_adapter
          board: nice_nano_v2
