name: Build ZMK Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Checkout ZMK
        uses: actions/checkout@v3
        with:
          repository: zmkfirmware/zmk
          path: zmk

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip ninja-build gperf cmake dfu-util
          pip3 install --user west

      - name: Initialize West
        run: |
          mkdir workspace
          cd workspace
          west init -l ../zmk/app

      - name: Update West modules
        run: |
          cd workspace
          west update

      - name: Build left firmware
        run: |
          cd workspace
          west build -b nice_nano_v2 -- -DSHIELD=corne_left

      - name: Build right firmware
        run: |
          cd workspace
          west build -b nice_nano_v2 -- -DSHIELD=corne_right
